apiVersion: v1
kind: Pod
metadata:
  name: tetsing-emptydir
spec:
  containers:
  - name: empt-cont
    image: gcr.io/google_containers/test-webserver
    volumeMounts:
    - name:  cache-volume
      mountPath:  /cache
  volumes:
    - name: cache-volume
      emptyDir: {}
