apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: web
spec:
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - image: linuxacademycontent/kubectl-proxy
    name: proxy
  restartPolicy: Always